apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  containerRuntimeExecutor: k8sapi
  artifactRepository: |
    s3:
      bucket: argo-artifacts
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: minio
        key: accesskey
      secretKeySecret:
        name: minio
        key: secretkey